spring:
  profiles:
    active: core

---

server:
  port: 8080
spring:
  profiles: core
  datasource:
    url: 'jdbc:mariadb://116.123.4.39:33060/indian_poker?useUnicode=true&characterEncoding=utf8mb4'
    username: root
    password: ${env.DATABASE_PWD}
    driver-class-name: 'org.mariadb.jdbc.Driver'
  jpa:
    hibernate:
      naming:
        physical-strategy: 'indian.poker.game.spring.IndianNamingStrategyImpl'
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.MariaDB103Dialect'
    generate-ddl: true
    show-sql: true
user.root:
  email: ${env.USER_ROOT_EMAIL}
  saved: ${env.USER_ROOT_SAVED}
  name: ${env.USER_ROOT_NAME}
  key: ${env.SECRET_KEY}

---

server:
  port: 8080
spring:
  profiles: test
  datasource:
    url: 'jdbc:mariadb://116.123.4.39:33060/indian_poker_test?useUnicode=true&characterEncoding=utf8mb4'
    username: root
    password: ${env.DATABASE_PWD}
    driver-class-name: 'org.mariadb.jdbc.Driver'
  jpa:
    hibernate:
      naming:
        physical-strategy: 'indian.poker.game.spring.IndianNamingStrategyImpl'
      ddl-auto: create-drop
    database-platform: 'org.hibernate.dialect.MariaDB103Dialect'
    generate-ddl: true
    show-sql: true
user.root:
  email: ${env.USER_ROOT_EMAIL}
  saved: ${env.USER_ROOT_SAVED}
  name: ${env.USER_ROOT_NAME}
  key: ${env.SECRET_KEY}

